/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_as;

import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ING RUBER VILLAR PDA
 */
public class crud extends javax.swing.JFrame {

  Conexion con = new Conexion ();
  Connection cn;
  Statement st;
  ResultSet rs;
  DefaultTableModel modelo;
  int id;
  
    public crud() {
        initComponents();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnag = new javax.swing.JButton();
        btnmod = new javax.swing.JButton();
        brnelim = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(27, 239, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("DNI:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Nombre");

        txtnombre.setBackground(new java.awt.Color(204, 204, 255));
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtdni.setBackground(new java.awt.Color(204, 204, 255));
        txtdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdniActionPerformed(evt);
            }
        });

        txtid.setBackground(new java.awt.Color(204, 204, 255));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("CRUD");

        btnag.setBackground(new java.awt.Color(51, 51, 0));
        btnag.setForeground(new java.awt.Color(255, 255, 255));
        btnag.setText("AGREGAR");
        btnag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagActionPerformed(evt);
            }
        });

        btnmod.setBackground(new java.awt.Color(0, 0, 102));
        btnmod.setForeground(new java.awt.Color(255, 255, 255));
        btnmod.setText("MODIFICAR");
        btnmod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmodMouseClicked(evt);
            }
        });
        btnmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodActionPerformed(evt);
            }
        });

        brnelim.setBackground(new java.awt.Color(255, 0, 0));
        brnelim.setForeground(new java.awt.Color(255, 255, 255));
        brnelim.setText("ELIMINAR");
        brnelim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnelimActionPerformed(evt);
            }
        });

        btnnuevo.setBackground(new java.awt.Color(51, 102, 0));
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setText("NUEVO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        TablaDatos.setBackground(new java.awt.Color(204, 204, 255));
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "DNI"
            }
        ));
        TablaDatos.setToolTipText("");
        TablaDatos.setGridColor(new java.awt.Color(0, 255, 204));
        TablaDatos.setSelectionForeground(new java.awt.Color(204, 204, 255));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnag)
                                    .addGap(60, 60, 60)
                                    .addComponent(btnmod)
                                    .addGap(39, 39, 39)
                                    .addComponent(brnelim)
                                    .addGap(55, 55, 55)
                                    .addComponent(btnnuevo))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(57, 57, 57)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtid)
                                        .addComponent(txtnombre)
                                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(207, 207, 207)
                            .addComponent(jLabel4))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnag)
                    .addComponent(btnmod)
                    .addComponent(brnelim)
                    .addComponent(btnnuevo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagActionPerformed
        Agregar();
        listar();
         nuevo();
    }//GEN-LAST:event_btnagActionPerformed

    private void btnmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodActionPerformed
        modificar();
        listar();
        nuevo();
    }//GEN-LAST:event_btnmodActionPerformed

    private void txtdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdniActionPerformed

    private void brnelimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnelimActionPerformed
        eliminar();
        listar();
        nuevo();
    }//GEN-LAST:event_brnelimActionPerformed

    private void btnmodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodMouseClicked
        
      
    }//GEN-LAST:event_btnmodMouseClicked

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
         int fila = TablaDatos.getSelectedRow();
        if(fila== -1){
        
         JOptionPane.showMessageDialog(null, "Usuario no seleccionado ");
        }
        else{
            
        id = Integer.parseInt((String)TablaDatos.getValueAt(fila,0).toString());
        String nom = (String)TablaDatos.getValueAt(fila,1);
        String dni = (String)TablaDatos.getValueAt(fila,2);
        
        txtid.setText(""+id);
        txtnombre.setText(nom);
        txtdni.setText(dni);
        
        
       }
    }//GEN-LAST:event_TablaDatosMouseClicked

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_btnnuevoActionPerformed

    void listar(){
        String sql = "SELECT * FROM persona";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
           
            Object[] persona = new Object[3];
            modelo = (DefaultTableModel) TablaDatos.getModel();
            
            while(rs.next()){
                persona[0]= rs.getInt("id");
                persona[1]= rs.getString("nombre");
                persona[2]= rs.getString("dni");
                modelo.addRow(persona);
            }
            TablaDatos.setModel(modelo);
        }catch(Exception e){
    
        }
    }
    
    void Agregar(){
        String nom = txtnombre.getText();
        String dni = txtdni.getText();
    
        if(dni.equals("")||nom.equals("")){
            JOptionPane.showMessageDialog(null,"Las cajas estan vacias");
        }else{
            String sql = "INSERt INTO persona (nombre,dni) values ('"+nom+"','"+dni+"')";
            
            try{
            cn = con.getConnection();
            st = cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Usuario agregado");
            limpiar();
            }catch(Exception e){
            }
           
        }
    }
    void limpiar(){
        for(int i = 0 ; i<=TablaDatos.getRowCount(); i++){
            modelo.removeRow(i);
            i--;
        }
        
    }
    
    void modificar(){
        
        String nom = txtnombre.getText();
        String dni = txtdni.getText();
        
        
         String sql ="UPDATE persona set nombre ='"+nom+"' , dni='"+dni+"' WHERE id= "+id ;
        if( dni.equals("")||nom.equals("")){
        
        JOptionPane.showMessageDialog(null,"Ingresar datos");
        }else{
           
            try{
              
            cn = con.getConnection();
            st = cn.createStatement();
            st.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(null, "Usuario Actualizado");
            
            limpiar();
            
            }catch(Exception e){
                
            }
        
        }
    }
    
    void eliminar(){
        int filaseleccionada = TablaDatos.getSelectedRow();
        
        if(filaseleccionada == -1){
        
            JOptionPane.showMessageDialog(null, "Debe Seleccionar una fila");
        
        }else{ 
            String sql = "delete from persona where id ="+id;
            
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
            
             JOptionPane.showMessageDialog(null, "Usuario eliminado");
             limpiar();
            }catch(Exception e){
            
            
            }
            
        }
    }
    
    void nuevo(){
    txtid.setText("");
    txtnombre.setText("");
    txtdni.setText("");
    txtdni.requestFocus();
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton brnelim;
    private javax.swing.JButton btnag;
    private javax.swing.JButton btnmod;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
